name: PR
on: [push, pull_request]
jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.20
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: SBT Test
        run: sbt test
